# File: utils/pdf_maker.py
from fpdf import FPDF
from datetime import datetime

def generate_pdf_report(patient_name, age, sex, risk_level, probability, clinical_prob, ecg_prob):
    """Generates a professional PDF report and returns it as a downloadable byte string."""
    pdf = FPDF()
    pdf.add_page()
    
    # Fonts
    pdf.set_font("Arial", 'B', 16)
    
    # Title
    pdf.set_text_color(217, 4, 41) # Crimson Red
    pdf.cell(200, 10, txt="CardioGuard AI - Clinical Risk Report", ln=True, align="C")
    pdf.line(10, 25, 200, 25) # Separator Line
    
    # Patient Info
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(15)
    pdf.cell(200, 10, txt=f"Date: {datetime.now().strftime('%Y-%m-%d')}", ln=True)
    pdf.cell(200, 10, txt=f"Patient ID/Name: {patient_name}", ln=True)
    pdf.cell(200, 10, txt=f"Demographics: {age} years old | {sex}", ln=True)
    
    # Diagnosis Block
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="Final Multimodal Diagnosis:", ln=True)
    
    pdf.set_font("Arial", '', 12)
    pdf.cell(200, 10, txt=f"Risk Level: {risk_level}", ln=True)
    pdf.cell(200, 10, txt=f"Overall Heart Disease Probability: {probability:.1f}%", ln=True)
    
    # Detailed Breakdown
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="AI Expert System Breakdown:", ln=True)
    
    pdf.set_font("Arial", '', 12)
    pdf.cell(200, 10, txt=f"- Clinical Model (Vitals/Blood) Risk Indicator: {clinical_prob:.1f}%", ln=True)
    pdf.cell(200, 10, txt=f"- ECG Model (Imaging) Risk Indicator: {ecg_prob:.1f}%", ln=True)
    
    # Footer
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 10, txt="Disclaimer: This report is generated by an AI assistant and is intended to assist clinicians, not replace professional medical judgment.")
    
    # Output as string to allow Streamlit to download it
    return pdf.output(dest='S').encode('latin-1')